quarkus.index-dependency.rimfrost-framework-regel-manuell.group-id=se.fk.rimfrost.framework.regel.manuell
quarkus.index-dependency.rimfrost-framework-regel-manuell.artifact-id=rimfrost-framework-regel-manuell

quarkus.index-dependency.rimfrost-referensdata-erbjudande.group-id=se.fk.rimfrost.referensdata
quarkus.index-dependency.rimfrost-referensdata-erbjudande.artifact-id=rimfrost-template-referensdata-erbjudande

# TODO: Replace this index-dependency with one to rule-specific OpenAPI artifact
quarkus.index-dependency.rimfrost-template-regel-manuell-openapi-jaxrs-spec.group-id=se.fk.rimfrost.template.regel.manuell.openapi
quarkus.index-dependency.rimfrost-template-regel-manuell-openapi-jaxrs-spec.artifact-id=rimfrost-template-regel-manuell-openapi-jaxrs-spec

# Container image configuration
# TODO: Change container image name to something unique for the rule
quarkus.container-image.name=rimfrost-template-regel-manuell

# Kafka setup
# TODO: Change kafka source & subtopic to something unique for the rule
kafka.source=RegelTemplate
kafka.subtopic=regel-template

#Incoming
# TODO: Change request topic to something unique for the rule
mp.messaging.incoming.regel-requests.topic=regel-manuell-requests

mp.messaging.incoming.operativt-uppgiftslager-responses.topic=operativt-uppgiftslager-responses.${kafka.subtopic}
mp.messaging.incoming.operativt-uppgiftslager-status-notification.topic=operativt-uppgiftslager-status-notification.${kafka.subtopic}

#Outgoing
# TODO: Change response topic to something unique for the rule
mp.messaging.outgoing.regel-responses.topic=regel-manuell-responses

# Persistence
# TODO: Change schema and table-prefix to something unique for the rule
quarkus.flyway.default-schema=regel_regeltemplate
regel.persistence.table-prefix=regeltemplate

%prod.quarkus.datasource.username=${DB_USERNAME}
%prod.quarkus.datasource.password=${DB_PASSWORD}
%prod.quarkus.datasource.jdbc.url=${DB_URL}

# REST setup
handlaggning.api.base-url=http://rimfrost-k8s-handlaggning:8080
oul.api.base-url=http://rimfrost-k8s-uppgiftslager:8080
