quarkus.index-dependency.rimfrost-framework-regel-manuell.group-id=se.fk.rimfrost.framework.regel.manuell
quarkus.index-dependency.rimfrost-framework-regel-manuell.artifact-id=rimfrost-framework-regel-manuell

# Container image configuration
# TODO: Change container image name to something unique for the rule
quarkus.container-image.name=rimfrost-template-regel-manuell

# Kafka setup
# TODO: Change kafka source & subtopic to something unique for the rule
kafka.source=RegelTemplate
kafka.subtopic=regel-template

#Incoming
# TODO: Change request topic to something unique for the rule
mp.messaging.incoming.regel-requests.topic=regel-manuell-requests

mp.messaging.incoming.operativt-uppgiftslager-responses.topic=operativt-uppgiftslager-responses.${kafka.subtopic}
mp.messaging.incoming.operativt-uppgiftslager-status-notification.topic=operativt-uppgiftslager-status-notification.${kafka.subtopic}

#Outgoing
# TODO: Change response topic to something unique for the rule
mp.messaging.outgoing.regel-responses.topic=regel-manuell-responses

# REST setup
handlaggning.api.base-url=http://rimfrost-k8s-handlaggning:8080
